-- DECKS
create table if not exists public.decks (
  id text primary key,
  name text not null,
  color text not null,
  icon text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.decks enable row level security;

create policy "decks_select_own"
  on public.decks for select
  using (auth.uid() = user_id);

create policy "decks_insert_own"
  on public.decks for insert
  with check (auth.uid() = user_id);

create policy "decks_update_own"
  on public.decks for update
  using (auth.uid() = user_id);

create policy "decks_delete_own"
  on public.decks for delete
  using (auth.uid() = user_id);


-- CAPTURES
create table if not exists public.captures (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_path text,
  public_url text,
  created_at timestamptz not null default now(),
  uploaded bool not null default false,
  meta jsonb
);

alter table public.captures enable row level security;

create policy "captures_all_own"
  on public.captures for all
  using (auth.uid() = user_id);


-- OBJECT_LABELS
create table if not exists public.object_labels (
  id bigint primary key generated by default as identity,
  capture_id uuid not null references public.captures(id) on delete cascade,
  label text not null,
  confidence numeric,
  bbox jsonb,
  language text
);

alter table public.object_labels enable row level security;

create policy "object_labels_select_own"
  on public.object_labels for select
  using (
    exists (
      select 1 from public.captures 
      where captures.id = object_labels.capture_id 
      and captures.user_id = auth.uid()
    )
  );

create policy "object_labels_insert_own"
  on public.object_labels for insert
  with check (
    exists (
      select 1 from public.captures 
      where captures.id = object_labels.capture_id 
      and captures.user_id = auth.uid()
    )
  );

create policy "object_labels_update_own"
  on public.object_labels for update
  using (
    exists (
      select 1 from public.captures 
      where captures.id = object_labels.capture_id 
      and captures.user_id = auth.uid()
    )
  );

create policy "object_labels_delete_own"
  on public.object_labels for delete
  using (
    exists (
      select 1 from public.captures 
      where captures.id = object_labels.capture_id 
      and captures.user_id = auth.uid()
    )
  );